#include "global.h"
#include "functions.h"
#include "gba/io_reg.h"

void ModuleSetTrackBgCnt(void)
{
    REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
    REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
    REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
    REG_BG0CNT = BGCNT_CHARBASE(3) | BGCNT_SCREENBASE(28);
    REG_BLDALPHA = BLDALPHA_BLEND(8, 8);
    REG_BLDCNT = BLDCNT_TGT2_BG0 | BLDCNT_TGT2_BG1 | BLDCNT_TGT2_BG2 | BLDCNT_EFFECT_BLEND;
}
