#include "global.h"
#include "gba/io_reg.h"
#include "variables.h"

void SetTrackBgCnt(void)
{
    switch (gTrackId) {
        case 0:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(29);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 1:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 2:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 3:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 4:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 5:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 6:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 7:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 8:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 9:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_SCREENBASE(31);
            break;
        case 10:
        case 11:
            REG_BG3CNT = BGCNT_PRIORITY(3) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(61);
            REG_BG2CNT = BGCNT_PRIORITY(1) | BGCNT_SCREENBASE(30);
            REG_BG1CNT = BGCNT_PRIORITY(2) | BGCNT_CHARBASE(2) | BGCNT_SCREENBASE(31);
            break;
    }
    REG_BG0CNT = BGCNT_CHARBASE(3) | BGCNT_SCREENBASE(28);
    REG_BLDALPHA = BLDALPHA_BLEND(8, 8);
    REG_BLDCNT = BLDCNT_TGT2_BG0 | BLDCNT_TGT2_BG1 | BLDCNT_TGT2_BG2 | BLDCNT_EFFECT_BLEND;
}
