#ifndef GUARD_FUNCTIONS_H
#define GUARD_FUNCTIONS_H

// Game functions that have no module header yet, sorted by ROM
// address. Stage 1 catch-all of docs/extern-headers-plan.md.
struct Car;
struct CgbChannel;
struct CornerSweep;
struct DamageSmoke;
struct DraftStreak;
struct LanePos;
struct LaneSeg;
struct MusicPlayerInfo;
struct MusicPlayerTrack;
struct ObjTileCacheEntry;
struct SkidSmoke;
struct SongHeader;
struct SoundInfo;
struct SweepBox;
struct Task;
struct WallHit;

// Main program

/* The SDK start routine (lib/crt0.s) and both hosted front ends call
   this; the front ends used to keep local externs, but two front ends
   (src/platform/pret_sdl/sdl2.c, src/platform/null_front/null_front.c)
   is one local declaration too many for scripts/externs.py. */
void AgbMain(void);

void SetLinkSerialIntr(void);
void InitIntrHandlers(void);
void SetVBlankCallback(void (*callback)(void));
void WaitForVBlank(void);
void ReadKeys(void);
s32 umul3232H32(s32 a, s32 b);
void sub_08001134(struct MusicPlayerInfo *mplayInfo);
void MPlayFadeOut(struct MusicPlayerInfo *r0, u16 v);
void m4aSoundMain(void);
void m4aSongNumStop(u16 a);
u32 MidiKeyToCgbFreq(u8 chanNum, u8 key, u8 fineAdjust);
void CgbOscOff(u8 chanNum);
void CgbModVol(struct CgbChannel *chan);
void CgbSound(void);
void ply_memacc(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ply_xcmd(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ply_xxx(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ply_xwave(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ply_xtype(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ply_xatta(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ply_xdeca(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ply_xsust(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ply_xrele(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ply_xiecv(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ply_xiecl(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ply_xleng(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ply_xswee(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void DummyCgbSound(void);
u8 Random8(void);
void GameMain(void);
void SetTrackBgCnt(void);
void EnableRaceDisplay(void);
void StopAllSongsAtRaceStart(void);
u8 RunRace(u32 a, u8 b, void *unused);
void MainVBlankCallback(void);
u16 PackLinkKeys(u16 keys);
u32 UnpackLinkKeys(u16 a);
u8 IsValidLinkKeys(u16 keys);
s32 ExchangeLinkInput(void);
u8 StartSinglePakLink(void);
void LoadTrack(u32 idx);
void UpdateTrackScroll(u32 unused0, u32 unused1);
void DrawTrackMapWindow(u32 x, u32 y, u8 *map, u32 *dest, u8 *charBase, u16 unused);
void FlushTilemapBuffer(u8 *src, u8 *dest);
void FlushTrackBgBuffers(void);
void LoadFadePalette(u16 *r4);
void FillFadePalette(u16 color);
void BeginFadeToColor(s32 a, u32 b);
void BeginFadeToBrightenedPalette(s32 arg0, u16 *src);
void SetFadeDeltasColors240To255(u32 a);
void UpdatePaletteFade(void);
void FlushPaletteBuffer(void);
void FadeToColor(u32 r0, u32 r1);
void FadeToBrightenedPalette(void *a, u32 b);
void SetCameraPos(u32 x, u32 y);
void UpdateCameraScroll(void);
void SmoothCamera(void);
void SetCameraTarget(struct Car *arg0);
void ClearOamBuffer(void);
u32 AddOamEntry(u32 a, u32 b);
u32 AddDepthSortedSprite(u32 attr01, u32 attr2, u16 depth);
void ResetSpriteOrderTable(void);
void FlushSortedSprites(void);
void UpdateSprites(void);
void DrawTrackCueIcon(u8 cueId, u16 angle);
void LoadTrackCues(u8 a);
void UpdateTrackCues(struct Car *car);
void ClearPauseMenuBox(void);
void sub_08004A7C(u8 sel);
void sub_08004B1C(u8 arg);
void DrawPauseMenu(u8 arg);
void DrawPauseConfirmMenu(u8 arg);
u16 ReadLinkMenuKeys(void);
u8 PauseConfirmMenu(void);
u8 PauseMenu(void);
u8 LinkPauseConfirmMenu(void);
u8 LinkPauseMenu(void);
u8 SinglePakPauseMenu(void);
void DrawTime(u16 *dest, s32 a, s32 b, s32 c);
void WaitForLinkRestart(void);
void DrawLinkFinishTimes(void);
void ResetLapTimer(void);
void ResetRaceTimer(void);
void SetCountdownSeconds(u8 x);
void InitCountdown(void);
void CheckTrackRecord(u16 a1, u16 a2, u16 a3);
void UpdateRaceTimers(void);
void DrawBigDigit(u16 *dest, u8 idx);
void DrawSmallDigit(u16 *dest, u8 idx);
void DrawSpeedNeedle(u32 speed);
void DrawPitStopWarning(struct Car *car);
void DummyHudHook(struct Car *unused);
void DrawLowFuelWarning(s32 fuel);
void DrawRacePosition(s32 arg);
void DrawLapCounter(s32 a, s32 b);
void DrawTireWear(struct Car *p);
void UpdateRaceHud(void);
void ClearTextLayer(void);
void InitRaceHud(void);
void InitTimeTrialHud(void);
void ClearRaceTextLayer(void);
void DrawText(const u8 *text, u32 x, u32 y, u8 highlight);
void DrawTextCentered(const u8 *str, u32 y, u32 unused);
void DrawTextAt(const u8 *str, u32 x, u32 y);
void DrawBigText(const u8 *text);
void DummyUiFontLoad(const u8 *unused);
void DrawTextCenteredHighlight(const u8 *text, u32 y, u8 highlight);
void LoadTrackSegs(u32 trackId);
u8 UpdateLapProgress(struct Car *p, u8 a1);
void InitGfxCaches(void);
void AgeGfxCaches(void);
struct ObjTileCacheEntry *RequestObjTiles64(GfxSrc gfx, u8 flag);
struct ObjTileCacheEntry *RequestObjTiles16(GfxSrc gfx);
struct ObjTileCacheEntry *RequestObjTiles2(GfxSrc gfx);
struct ObjTileCacheEntry *RequestObjTiles8(GfxSrc gfx);
struct ObjTileCacheEntry *RequestObjTiles4(GfxSrc gfx);
struct ObjTileCacheEntry *RequestObjTiles1(GfxSrc gfx);
struct ObjTileCacheEntry *RequestObjTiles1Compressed(GfxSrc gfx);
u8 RequestObjPalette(const void *a);
void UploadPendingGfx(void);
void InitTasks(void);
void *AllocTask(void);
void FreeTask(void *task);
void AddTask(void *task);
void RemoveTask(void *task);
void RunTasks(void);
u8 FindFreePitStall(u8 unused);
u8 CarNeedsPit(struct Car *a1);
void AwardRacePoints(struct Car *a1, u32 a2);
void BuildStartingGrid(u8 a1);
void UpdateCarSurface(struct Car *car);
void ClearPitMenu(void);
void DrawPitMenu(u8 a);
void InitPitMenu(void);
void UpdatePitMenu(void);
void ComputeGearRatioReciprocals(u16 *a1, u16 *a2);
void InitTuneSettings(void);
void SetAiDriverGearTables(struct Car *car);
void SetTireGrip(struct Car *car, u8 carIndex);
void UpdateTireForces(struct Car *car, u8 carIndex);
void ComputeAxleTireForce(u8 axle, struct Car *car);
void AssignRandomDrivers(void);
void FillUnassignedDrivers(void);
u8 IsProgressPointCrossed(s32 v);
u8 IsChallengeTimeWithin(s32 arg0);
void DrawChallengeTimer(void);
void DrawChallengeSpeed(s32 x);
void ClearChallengeSpeed(void);
void UpdateChallengeTimer(void);
void ResetChallengeTimer(void);
s32 GetAverageWaypointSpeed(void);
void ClearWaypointSpeedSamples(void);
void UpdateChallenge(void);
void InitRaceCars(u32 a1);
void ClearPitStopProgressBar(void);
void DrawPitStopProgressBar(u8 arg);
void EnterPit(struct Car *car, u8 stall);
void UpdatePitStop(struct Car *a1, u8 a2);
void InitCar(u8 a, struct Car *car, s32 b, s32 c, u32 d, u32 unused);
void UpdateRacePosition(u8 idx);
u32 WorldToScreen(s32 x, s32 y, s32 *out);
void DrawCar(struct Car *car, u8 idx);
void DrawAllCars(void);
void DrawLinkMarker(u32 x, u32 y, u32 carIdx);
void UpdateEngine(struct Car *car, s32 mode);
void ComputeForwardSpeed(struct Car *a);
void ComputeCarCorners(struct Car *obj);
void RecordFinishTime(struct Car *obj);
void StopCar(struct Car *p);
void UpdateCar(struct Car *car, u8 idx);
void UpdateAllCars(void);
void AddDemoEndTask(void);
void EndRace(void);
void RaceStartSplashTask(struct Task *task);
void LinkRaceStartSplashTask(struct Task *task);
void StartRace(void);
void InitLinkRaceStart(void);
void DrawLapTime(s32 a, s32 b, s32 c);
void LapSnapshotTask(struct Task *e);
void SaveLapTime(void);
void AddTrackRecordTasks(void);
void DummyWallHitHook(s32 unused0, s32 unused1);
void AddDraftStreakTask(u8 carIdx, u8 cornerIdx);
void DraftStreakTask(struct DraftStreak *e);
void AddSkidSmokeTask(u8 carIdx, u8 cornerIdx);
void SkidSmokeTask(struct SkidSmoke *e);
void AddDamageSmokeTask(struct Car *car);
void DamageSmokeTask(struct DamageSmoke *e);
void DummyCarHitHook(s32 unused0, s32 unused1, s32 unused2, s32 unused3, s32 unused4, s32 unused5, s32 unused6);
void DrawSpriteText(u8 *a, u32 b, u32 c);
s32 WorldToLaneDistance(s32 posX, s32 posZ, const u16 *points, const struct LaneSeg *seg, s32 unused);
void GetLanePositionAtDistance(s32 x, struct LanePos *out, const u16 *points, const struct LaneSeg *segments);
void SetCarLane(struct Car *car, s32 lanePosition);
void PlaceCarsAlongLane(struct Car **arr, s32 a1, s32 a2, s32 a3, u8 a4);
void SetCarLaneByIndex(struct Car *car, u8 laneIdx);
void WorldToCarLocal(struct Car *car, s32 x, s32 z, s32 *out);
s32 CheckDrafting(struct Car *car);
void UpdateCarPredictedPos(struct Car *car);
s32 FindClosestLaneSegment(struct Car *car, s32 unused);
s32 ComputePitStallDistance(struct Car *car);
void UpdateAiDriver(struct Car *ent, u8 param);
void InitCarSteering(s32 *steer, u32 heading);
s32 Atan2(s32 x, s32 y);
u8 GetTrackTileType(s32 x, s32 y);
void LoadTrackWalls(u32 idx);
s32 TestCornersVsWalls(struct CornerSweep *corn, struct SweepBox *box, struct SweepBox *cbox, struct WallHit *out,
                       u16 *wallList, s32 *best);
s32 CollideCarWithWalls(struct Car *a);
void BuildCarCollFrame(struct Car *car, s32 *frame);
u8 CollideCars(struct Car *car);
void DrawMultibootProgressMarker(u32 x, u32 y);
void DrawLinkProgressBar(u16 progress, u16 y);
void InitSinglePakLinkScreen(void);
u32 SendMultibootPayload(void);
u8 SendMultibootIsland(void);
void SioTransferInit(u32 send, const void *chunk);
u32 SioTransferUpdate(u32 *a1);
void SioTransferIntr(void);
void DummyCarDamageHook(s32 unused0, u8 unused1);
void DummyMainMenuHook(void);
void sub_0800EA64(void *a1);
u32 sub_0800EAA0(void *a1);
void sub_0800EEFC(u8 *a1, const u8 *a2, s32 a3, u32 a4, u32 a5);
u32 sub_0800EFC0(u8 *ptr);
const u8 *GetDriverName(u8 driverId);
u8 FindDriverByTeam(u8 teamId);
void UnlockChampionshipTier(u8 param);
u8 IsAnyChampionshipTeamAvailable(void);
void ShowKickedFromTeamMessage(void);
void ShowStayOnTeamMessage(void);
void DrawCareerDecision(u8 a);
u8 CareerDecisionMenu(void);
u8 ResolveSeasonResult(u8 championshipIndex, u8 finishPos);
void BuildScreenPalette(const void *src, u16 *dst);
void ZeroTextLayer(void);
void SortCarsByTime(void);
void LoadMainMenuBackdrop(void);
void LoadResultsScreenBackdrop(void);
void LoadMenuBackdrop(void);
void ShowBootSplash1(void);
void ShowCreditsPage1(void);
void ShowCreditsPage2(void);
void ShowCreditsPage3(void);
void InitMultiplayerSio(void);
void SioSendWord(u16 data);
void SerialIntr(void);
void SetupChallenge(u8 a, u8 *unused);
void StopAllSongsAndVSyncOff(void);
void StopAllSongs(void);
void StartMenuMusic(void);
void DrawCachedSprite(u32 posX, u32 posY, GfxSrc gfxId, const void *palette, u8 hflip);
void Draw64x64Sprite(u32 a, u32 b, u32 c);
void Draw32x32Sprite(u32 posX, u32 posY, u32 tileNum);
void WaitFrames(s32 n);
void WaitFramesOrKey(s32 count);
void ShowBootSplash3(void);
void ShowBootSplash2(void);
u8 TitleScreen(void);
void DrawMainMenuItems(u8 selected);
void DrawMainMenu(u8 a);
void DrawBackdropMetatileMap(const u16 *data);
void DrawMetatileMap(const u16 *src, const u16 *tiles);
u8 LinkTrackSelect(void);
void DrawTeamSelectInfo(u8 idx);
u16 FindTeamDriverPair(u8 id);
u32 DrawTeamSelect(u8 param);
u8 TeamSelectMenu(void);
u8 DrawDriverSelect(u8 a);
u8 DriverSelectMenu(void);
u8 DrawTrackSelect(u8 a, u8 b);
u8 TrackSelectMenu(u8 a, u8 b);
void SortLinkCarsByTime(void);
void DrawLinkRaceSummary(void);
u8 ShowLinkRaceSummary(void);
void DrawLinkPostRaceMenu(u8 a);
u8 LinkPostRaceMenu(void);
s16 LinkMenuMoveHorizontal(u16 keys, s16 v, s16 lo, s16 hi, u8 f, u8 e);
s16 LinkDriverSelect(void);
void ResetLinkState(void);
void DetectLinkPlayers(void);
u16 RgbFromPercent(u16 a, u16 b, u16 c);
void LoadMenuScreen(u8 a, u16 *dst);
s16 MenuMoveVertical(u16 keys, s16 v, s16 lo, s16 hi);
s16 MenuMoveVerticalSilent(u16 keys, s16 v, s16 lo, s16 hi);
s16 MenuMoveHorizontal(u16 keys, s16 v, s16 lo, s16 hi);
s16 MenuMoveHorizontalSilent(u16 keys, s16 v, s16 lo, s16 hi);
s16 MenuMoveHorizontalClamped(u16 keys, s16 v, s16 lo, s16 hi);
void DrawMultiplayerMenu(u8 a);
s8 MultiplayerMenu(void);
s32 UpdateLinkLobby(void);
void DrawLinkLobby(u8 unused);
u8 LinkLobby(void);
void InitNewSaveData(void);
void DrawOptionsMenu(u32 a);
u8 OptionsMenu(void);
void sub_0801264C(u32 x);
void sub_08012758(void);
void DrawChampionshipQualifyResult(s8 a);
void ShowChampionshipQualifyResult(s8 a);
u8 RunChampionshipQualifyTest(u8 unused);
void DrawChallengeCategoryComplete(u8 a);
u8 ShowChallengeCategoryComplete(u8 category);
void DrawMessageBox(const u8 *title, const u8 *line1, const u8 *line2);
u8 MessageBox(const u8 *title, const u8 *line1, const u8 *line2);
void DrawChallengePassed(u8 unused1, u8 unused2);
void DrawChallengeFailed(u8 unused);
u8 ShowChallengePassed(u8 challengeIdx, u8 alreadyBeaten);
u32 GetPlayerStanding(void);
void DrawTrophyScreen(u32 a);
u8 TrophyScreen(u8 place);
void sub_08012DEC(u8 a);
void sub_08012EE8(u32 unused, u8 v);
void sub_08012FB0(void);
void sub_080130C8(u8 a);
s8 sub_0801319C(void);
void sub_080131F8(u8 arg);
void DrawCareerSessionMenu(u8 cursor, u8 unused0, u8 unused1);
s8 CareerSessionMenu(u8 qualifyDone, u8 practiceDone);
void DrawSeasonSessionMenu(u8 cursor, u8 unused0, u8 unused1);
s8 SeasonSessionMenu(u8 qualifyDone, u8 practiceDone);
void DrawCareerOverwriteConfirm(u8 a);
u8 CareerOverwriteConfirm(void);
void DrawSaveCareerStatus(u8 a);
s8 SaveCareerScreen(void);
void sub_080139F0(void);
void SortCarsByPoints(void);
void DrawQualifyResults(u8 a);
u8 QualifyResultsScreen(void);
void DrawRaceResults(u8 a);
u8 RaceResultsScreen(void);
u32 AwardAllRacePoints(void);
void DrawStandings(u8 a);
u8 StandingsScreen(void);
void sub_08014374(void);
void DrawTimeTrialMenu(u8 a);
u8 TimeTrialMenu(void);
void DrawChallengeCategorySelect(u32 a);
u8 ChallengeCategorySelect(void);
void DrawChallengeSelect(u8 a, u8 b);
u8 ChallengeSelect(u8 category, u8 challengeIdx);
void sub_08014944(u8 a);
void DrawNewGameLoadMenu(u8 a);
u8 NewGameLoadMenu(void);
void sub_08014B14(void);
void sub_08014BA0(void);
void DrawSingleRaceResultsPage(u8 a);
u8 SingleRaceResultsScreen(void);
void DrawSingleRaceRetryMenu(u8 a);
u8 SingleRaceRetryMenu(void);
void sub_08015000(u8 a);
void sub_080150F4(void);
void ResetBgScroll(void);
u32 MainMenuLoop(void);
void sub_08016330(u8 x);
void LinkFailScreen(void);
const u8 *GetString(u16 idx);
void WriteSaveBlocks(u16 a, u16 b);
void ReadSaveBlocks(u16 a, u16 b);
u32 InitEeprom(void);
u32 IsSeasonSaved(void);
void SaveSeason(void);
void LoadSeason(void);
void LoadTrackRecords(void);
void SaveTrackRecords(void);
void LoadProgress(void);
void SaveProgress(void);
void LoadOptions(void);
void SaveOptions(void);
void FormatSave(void);
u8 IsSaveValid(void);
u32 RandomInRange(u32 a, u32 b);
void SplitMilliseconds(s32 a, u16 *b, u16 *c, u16 *d);
void RandomizeAiFinishTimes(void);
u32 ComputeProgressDistance(s32 a, u8 b);
void FinishAllCars(u8 a);
void sub_08016E10(const void *src, void *dest, u32 control);
void VBlankIntrWait(void);
s32 sub_08017230(s32 a, s32 b);
s32 sub_080172C8(s32 a, s32 b);

#if PORTABLE
/* A spin on gVBlankWorkDone (src/race/RunRace.c): on the GBA the VBlank
   interrupt's callback (MainVBlankCallback) sets the flag while the game
   idles, so the loop is a plain wait. Hosted, that callback runs only
   from the front end's frame pump, so the spin pumps one frame per pass
   (VBlankIntrWait) - the same instant the hardware would deliver the
   interrupt - or it never ends. The caller's variables.h declares
   gVBlankWorkDone; the file-local goto-spin menus (src/menu, src/link)
   spell the same fix out inline instead. */
#define HOST_WAIT_VBLANK()                      \
    do {                                        \
        (*(vu8 *)&gVBlankWorkDone) = 0;         \
        while ((*(vu8 *)&gVBlankWorkDone) == 0) \
            VBlankIntrWait();                   \
    } while (0)
#endif

// High module (links at its EWRAM run address)

/* Localized message ids: rows of gModule_LocalizedText[8][5] (EN/FR/DE/ES/IT). */
#define MODULE_MSG_LINK_FAIL 0
#define MODULE_MSG_WAITING 1
#define MODULE_MSG_PRESS_START 2
#define MODULE_MSG_PAUSE 3
#define MODULE_MSG_RACE_OVER 4
#define MODULE_MSG_OUT_OF_TIME 5
#define MODULE_MSG_LAP_TIME 6
#define MODULE_MSG_CHECKPOINT 7

void ModuleSetLinkSerialIntr(void);
void ModuleInitIntrHandlers(void);
void ModuleSetVBlankCallback(void (*callback)(void));
void ModuleWaitForVBlank(void);
void ModuleReadKeys(void);
s32 sub_08339B78(s32 a, s32 b);
void sub_0833A7F4(struct MusicPlayerInfo *mplayInfo);
void ModuleMPlayFadeOut(u32 mplayInfo, u16 fadeOutDelay);
void ModuleM4aSoundInit(void);
void ModuleM4aSoundMain(void);
void ModuleM4aSongNumStart(u16 idx);
void ModuleM4aMPlayFadeOut(u32 mplayInfo, u16 fadeOutDelay);
void ModuleMPlayExtender(struct CgbChannel *cgbChans);
void ModuleClear64byte(void *x);
void ModuleSoundInit(struct SoundInfo *soundInfo);
void ModuleSampleFreqSet(u32 freq);
void ModuleM4aSoundMode(u32 mode);
void ModuleM4aSoundVSyncOff(void);
void ModuleM4aSoundVSyncOn(void);
void ModuleMPlayOpen(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *tracks, u32 r2);
void ModuleMPlayStart(struct MusicPlayerInfo *mplayInfo, struct SongHeader *songHeader);
void ModuleM4aMPlayStop(struct MusicPlayerInfo *mplayInfo);
void ModuleFadeOutBody(struct MusicPlayerInfo *mplayInfo);
void ModuleTrkVolPitSet(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
u32 ModuleMidiKeyToCgbFreq(u8 chanNum, u8 key, u8 fineAdjust);
void ModuleCgbOscOff(u8 chanNum);
void ModuleCgbModVol(struct CgbChannel *chan);
void ModuleCgbSound(void);
void ModuleM4aMPlayPitchControl(struct MusicPlayerInfo *mplayInfo, u16 trackBits, s16 pitch);
void ModulePlyMemacc(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ModulePlyXcmd(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ModulePlyXxx(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ModulePlyXwave(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ModulePlyXtype(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ModulePlyXatta(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track);
void ModulePlyXdeca(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ModulePlyXsust(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ModulePlyXrele(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ModulePlyXiecv(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ModulePlyXiecl(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ModulePlyXleng(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ModulePlyXswee(struct MusicPlayerInfo *unused, struct MusicPlayerTrack *track);
void ModuleDummyCgbSound(void);
u8 sub_0833BCBC(void);
void ModuleSortLinkCarsByTime(void);
const u8 *ModuleGetString(u16 messageId);
void ModuleGameMain(void);
void ModuleSetTrackBgCnt(void);
void ModuleEnableRaceDisplay(void);
u8 ModuleRunRace(u8 isDemo, u8 gameMode, void *unused);
void ModuleMainVBlankCallback(void);
u16 ModulePackLinkKeys(u16 keys);
u16 ModuleUnpackLinkKeys(u16 packed);
s32 ModuleExchangeLinkInput(void);
void ModuleLoadTrack(u32 idx);
void ModuleUpdateTrackScroll(u32 unused0, u32 unused1);
void ModuleDrawTrackMapWindow(u32 tileX, u32 tileY, u8 *map, u32 *dest, u32 *charBase, u16 unused);
void ModuleFlushTilemapBuffer(u8 *src, u8 *dest);
void ModuleFlushTrackBgBuffers(void);
void ModuleFillFadePalette(u32 color);
void ModuleBeginFadeToColor(u32 a0, u32 a1);
void ModuleBeginFadeToBrightenedPalette(s32 steps, u16 *src);
void ModuleSetFadeDeltasColors240To255(s32 steps);
void ModuleUpdatePaletteFade(void);
void ModuleFlushPaletteBuffer(void);
void ModuleFadeToColor(u32 color, u32 steps);
void ModuleSetCameraPos(u32 x, u32 y);
void ModuleUpdateCameraScroll(void);
void ModuleSmoothCamera(void);
void ModuleSetCameraTarget(struct Car *car);
void ModuleClearOamBuffer(void);
u32 ModuleAddOamEntry(u32 attr01, u32 attr2);
u32 ModuleAddDepthSortedSprite(u32 attr01, u32 attr2, u16 depth);
void ModuleResetSpriteOrderTable(void);
void ModuleFlushSortedSprites(void);
void ModuleUpdateSprites(void);
void ModuleLoadTrackCues(u32 unused);
void ModuleUpdateTrackCues(struct Car *unused);
void sub_0833DA2C(void);
u16 ModuleReadLinkMenuKeys(void);
u32 ModulePauseMenu(void);
u32 ModuleLinkPauseMenu(void);
u32 ModuleSinglePakPauseMenu(void);
void ModuleDrawTime(u16 *dest, s32 min, u32 sec, u32 ms);
void ModuleWaitForLinkRestart(void);
void ModuleDrawLinkFinishTimes(void);
void ModuleResetLapTimer(void);
void ModuleResetRaceTimer(void);
void ModuleSetCountdownSeconds(u8 value);
void ModuleInitCountdown(void);
void ModuleSetTrackRecord(u32 min, u32 sec, u32 ms);
void ModuleCheckTrackRecord(u16 a, u16 b, u16 c);
void ModuleUpdateRaceTimers(void);
void ModuleDrawBigDigit(u16 *dest, u8 idx);
void ModuleDrawSmallDigit(u16 *a, s32 b);
void ModuleDrawSpeedNeedle(u32 speed);
void ModuleDrawPitStopWarning(struct Car *car);
void ModuleDummyHudHook(struct Car *unused);
void ModuleDrawLowFuelWarning(s32 fuel);
void ModuleDrawRacePosition(s32 position);
void ModuleDrawLapCounter(s32 lap, s32 totalLaps);
void ModuleDrawTireWear(struct Car *p);
void ModuleClearTextLayer(void);
void ModuleInitRaceHud(void);
void ModuleInitTimeTrialHud(void);
void ModuleClearRaceTextLayer(void);
void ModuleDrawTextCenteredHighlight(const u8 *str, u32 y, u32 unused);
void ModuleDrawText(const u8 *text, u32 x, u32 y);
void ModuleLoadTrackSegs(u32 trackId);
u8 ModuleUpdateLapProgress(struct Car *p, u8 carIdx);
void ModuleInitGfxCaches(void);
void ModuleAgeGfxCaches(void);
struct ObjTileCacheEntry *ModuleRequestObjTiles16(GfxSrc gfx);
struct ObjTileCacheEntry *ModuleRequestObjTiles2(GfxSrc gfx);
struct ObjTileCacheEntry *ModuleRequestObjTiles8(GfxSrc gfx);
struct ObjTileCacheEntry *ModuleRequestObjTiles4(GfxSrc gfx);
struct ObjTileCacheEntry *ModuleRequestObjTiles1(GfxSrc gfx);
u8 ModuleRequestObjPalette(const void *palette);
void ModuleUploadPendingGfx(void);
void ModuleInitTasks(void);
void *ModuleAllocTask(void);
void ModuleFreeTask(void *task);
void ModuleAddTask(void *task);
void ModuleRemoveTask(void *task);
void ModuleRunTasks(void);
u8 ModuleFindFreePitStall(u8 unused);
u8 ModuleCarNeedsPit(struct Car *car);
void ModuleBuildStartingGrid(u8 idx);
void ModuleResetCarSurface(struct Car *car);
void sub_0834047C(u16 *a, u16 *b);
void ModuleSetTireGrip(struct Car *car, u8 b);
void ModuleUpdateTireForces(struct Car *car, u8 carIndex);
void ModuleComputeAxleTireForce(u8 axle, struct Car *car);
u8 ModuleIsProgressPointCrossed(s32 v);
u8 ModuleIsChallengeTimeWithin(s32 arg0);
void ModuleDrawChallengeTimer(void);
void ModuleDrawChallengeSpeed(u32 a1);
void ModuleClearChallengeSpeed(void);
void ModuleUpdateChallengeTimer(void);
void ModuleResetChallengeTimer(void);
u32 ModuleGetAverageWaypointSpeed(void);
void ModuleUpdateChallenge(void);
void ModuleInitRaceCars(u32 trackIdx);
void ModuleEnterPit(struct Car *unused0, u8 unused1);
void ModuleInitCar(u8 carIdx, struct Car *car, s32 posX, s32 posZ, u32 heading, u32 unused);
void ModuleUpdateRacePosition(u8 idx);
u8 ModuleWorldToScreen(s32 x, s32 y, s32 *out);
void ModuleDrawAllCars(void);
void ModuleDrawLinkMarker(u32 x, u32 y, u32 carIdx);
void ModuleUpdateEngine(struct Car *car, s32 mode);
void ModuleComputeForwardSpeed(struct Car *car);
void ModuleComputeCarCorners(struct Car *car);
void ModuleRecordFinishTime(struct Car *p);
void ModuleStopCar(struct Car *car);
void ModuleUpdateAllCars(void);
void ModuleAddDemoEndTask(void);
void ModuleEndRace(void);
void ModuleRaceStartSplashTask(struct Task *task);
void ModuleLinkRaceStartSplashTask(struct Task *task);
void ModuleStartRace(void);
void ModuleInitLinkRaceStart(void);
void ModuleDrawLapTime(u32 a0, u32 a1, u32 a2);
void ModuleSaveLapTime(void);
void ModuleAddTrackRecordTasks(void);
void ModuleDummyWallHitHook(s32 cornerX, s32 cornerZ);
void ModuleAddDraftStreakTask(u8 carIdx, u8 cornerIdx);
void ModuleAddSkidSmokeTask(u8 carIdx, u8 cornerIdx);
void ModuleAddDamageSmokeTask(struct Car *car);
void ModuleDummyCarHitHook(s32 unused0, s32 unused1, s32 unused2, s32 unused3, s32 unused4, s32 unused5, s32 unused6);
void ModuleDrawSpriteText(const u8 *a, u32 b, u32 c);
s32 ModuleCheckDrafting(struct Car *car);
void ModuleInitCarSteering(s32 *steer, u32 heading);
u8 ModuleGetTrackTileType(s32 x, s32 y);
void ModuleLoadTrackWalls(u32 idx);
s32 ModuleTestCornersVsWalls(struct CornerSweep *corn, struct SweepBox *box, struct SweepBox *cbox, struct WallHit *out,
                             u16 *wallList, s32 *best);
s32 ModuleCollideCarWithWalls(struct Car *a);
void ModuleBuildCarCollFrame(struct Car *car, s32 *frame);
u8 ModuleCollideCars(struct Car *car);
void sub_083446C8(u8 param);
void sub_08344730(void);
void sub_08344734(void);
void ModuleInitMultiplayerSio(void);
void ModuleSioSendWord(u16 data);
void ModuleSerialIntr(void);
void ModuleLinkHandshake(void);
void sub_08344B60(const void *src, void *dest, u32 control); /* CpuFastSet */
void sub_08344B64(const void *src, void *dest, u32 control); /* CpuSet */
void sub_08344B68(u32 clearFlags, u32 flags);                /* IntrWait */
void sub_08344B70(const void *src, void *dest);              /* RLUnCompVram */
void sub_08344B74(void);                                     /* VBlankIntrWait */
s32 sub_08344BB8(s32 a, s32 b);
s32 sub_08344C50(s32 a, s32 b);

// Multiboot island (links at its EWRAM run address)

void IslandDrawMultibootProgressMarker(s16 x, u8 y);
void IslandDrawLinkProgressBar(u16 progress, u16 y);
void IslandSioTransferInit(u32 send, void *chunk);
u32 IslandSioTransferUpdate(u32 *chunkSize);
void sub_083647F8(const void *src, void *dest, u32 control); /* CpuFastSet */
void sub_083647FC(const void *src, void *dest, u32 control); /* CpuSet */
void sub_08364800(const void *src, void *dest);              /* LZ77UnCompVram */
void sub_08364804(u32 resetFlags);                           /* RegisterRamReset */
void sub_08364808(void);                                     /* VBlankIntrWait */

#endif
